spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_retail?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 156001
  output:
    ansi:
      enabled: always
site:
  staticServer: http://static.xbb.com/retail
  staticFilePath: D:\xbb\server\nginx-1.14.2\html\retail
logging:
  level:
    club.xyes.zkh.retail: debug